name: mywatchcalendar
description: "TV Series Watchlist and upcoming calendar"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.5
  http: ^1.6.0
  url_launcher: ^6.3.2
  home_widget: ^0.9.3
  workmanager: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  change_app_package_name: ^1.5.0
  flutter_native_splash: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/launcher-icon.png

flutter_launcher_icons:
  image_path: "assets/launcher-icon.png"
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/launcher-icon.png"
    background_color: "#000000"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets/launcher-icon.png"
  macos:
    generate: true
    image_path: "assets/launcher-icon.png"

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#121212"

  image: assets/splash-screen.png
  image_dark: assets/splash-screen.png

  android_12:
    color: "#ffffff"
    color_dark: "#121212"
    image: assets/splash-screen.png
    image_dark: assets/splash-screen.png
    
  android: true
  ios: true
  web: false