name: Build and Release Flutter App

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build_and_release:
    name: Build APK and Web
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java (Required for Android build)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release --obfuscate --split-debug-info=build/symbols

      - name: Build Android APK arm64
        run: >
          flutter build apk --release --target-platform android-arm64 --split-per-abi
          --obfuscate --split-debug-info=build/symbols

      - name: Build Web App
        run: flutter build web --release --no-web-resources-cdn

      - name: Compress Web Build
        run: |
          cd build/web
          zip -r ../../web-release.zip .
          cd ../..

      - name: Compress Debug Symbols
        run: zip -r symbols.zip build/symbols

      - name: Upload Artifacts to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            web-release.zip
            symbols.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
